/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Luis1
 */
public class PainelAdministradorView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PainelAdministradorView.class.getName());

    /**
     * Creates new form PainelAdministradorView
     */
    public PainelAdministradorView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnManterUsuarios = new javax.swing.JButton();
        btnAutorizarNovoUsuario = new javax.swing.JButton();
        btnAlterarSenha = new javax.swing.JButton();
        btnVisualizarNotificacoes = new javax.swing.JButton();
        btnLimparSistema = new javax.swing.JButton();
        btnEnviarNotificacao = new javax.swing.JButton();
        btnConfiguracao = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblNome = new javax.swing.JLabel();
        lblBemVindo = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        btnNotificacoes = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Painel de Administrador");
        setPreferredSize(new java.awt.Dimension(500, 450));

        jLabel2.setText("Notificaçoes Pendentes:");

        btnManterUsuarios.setText("Manter Usuários");

        btnAutorizarNovoUsuario.setText("Autorizar Novo Usuário");
        btnAutorizarNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutorizarNovoUsuarioActionPerformed(evt);
            }
        });

        btnAlterarSenha.setText("Alterar Senha");

        btnVisualizarNotificacoes.setText("Visualizar Notificações");

        btnLimparSistema.setText("Limpar Sistema");

        btnEnviarNotificacao.setText("Enviar Notificação");

        btnConfiguracao.setText("Configurações");

        lblNome.setText("jLabel1");

        lblBemVindo.setText("Bem Vindo!");

        lblTipo.setText("Você é um administrador");

        btnNotificacoes.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnManterUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnAutorizarNovoUsuario))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnVisualizarNotificacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnEnviarNotificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnAlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnConfiguracao, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnLimparSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblBemVindo)
                .addGap(190, 190, 190)
                .addComponent(jLabel2))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btnNotificacoes))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblTipo))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManterUsuarios)
                    .addComponent(btnAutorizarNovoUsuario))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVisualizarNotificacoes)
                    .addComponent(btnEnviarNotificacao))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAlterarSenha)
                    .addComponent(btnConfiguracao))
                .addGap(37, 37, 37)
                .addComponent(btnLimparSistema)
                .addGap(48, 48, 48)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBemVindo)
                    .addComponent(jLabel2))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNome)
                    .addComponent(btnNotificacoes))
                .addGap(6, 6, 6)
                .addComponent(lblTipo))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAutorizarNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutorizarNovoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAutorizarNovoUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PainelAdministradorView().setVisible(true));
    }

    public JButton getBtnManterUsuarios() {
        return btnManterUsuarios;
    }

    public JButton getBtnEnviarNotificacao() {
        return btnEnviarNotificacao;
    }

    public JButton getBtnAutorizarNovoUsuario(){
        return btnAutorizarNovoUsuario;
    }

    public JButton getBtnAlterarSenha() {
        return btnAlterarSenha;
    }
    
    public JButton getBtnConfiguracao() {
        return btnConfiguracao;
    }

    public JButton getBtnLimparSistema() {
        return btnLimparSistema;
    }

    public JButton getBtnVisualizarNotificacoes() {
        return btnVisualizarNotificacoes;
    }
    
    public JLabel getNome() {
        return lblNome;
    }
    public void setNome(String novoNome){
        lblNome.setText(novoNome);
    }
    public JButton getNotificacoes(){
        return btnNotificacoes;
    }
    public void setNotificacoes(String notificacoes){
        btnNotificacoes.setText(notificacoes);
    }
    /*
    public JLabel getTipo() {
        return lblNome;
    }
    public void setTipo(String novoTipo){
        lblNome.setText(novoTipo);
    }
    */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarSenha;
    private javax.swing.JButton btnAutorizarNovoUsuario;
    private javax.swing.JButton btnConfiguracao;
    private javax.swing.JButton btnEnviarNotificacao;
    private javax.swing.JButton btnLimparSistema;
    private javax.swing.JButton btnManterUsuarios;
    private javax.swing.JButton btnNotificacoes;
    private javax.swing.JButton btnVisualizarNotificacoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBemVindo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTipo;
    // End of variables declaration//GEN-END:variables
}
